name: gen
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  envied: ^1.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^1.0.0
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  very_good_analysis: ^7.0.0

flutter_gen:
  output: lib/src/asset/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true