import 'package:flutter/material.dart';

final class CustomColorScheme {
  CustomColorScheme._();

  static const lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff646116),
    surfaceTint: Color(0xff646116),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffebe68d),
    onPrimaryContainer: Color(0xff1e1c00),
    secondary: Color(0xff626042),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffe8e4be),
    onSecondaryContainer: Color(0xff1d1c05),
    tertiary: Color(0xff3e6655),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffc0ecd6),
    onTertiaryContainer: Color(0xff002116),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff410002),
    surface: Color(0xfffef9ec),
    onSurface: Color(0xff1d1c14),
    onSurfaceVariant: Color(0xff49473a),
    outline: Color(0xff7a7768),
    outlineVariant: Color(0xffcac7b5),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff323128),
    inversePrimary: Color(0xffceca74),
    primaryFixed: Color(0xffebe68d),
    onPrimaryFixed: Color(0xff1e1c00),
    primaryFixedDim: Color(0xffceca74),
    onPrimaryFixedVariant: Color(0xff4b4900),
    secondaryFixed: Color(0xffe8e4be),
    onSecondaryFixed: Color(0xff1d1c05),
    secondaryFixedDim: Color(0xffcbc8a4),
    onSecondaryFixedVariant: Color(0xff49482c),
    tertiaryFixed: Color(0xffc0ecd6),
    onTertiaryFixed: Color(0xff002116),
    tertiaryFixedDim: Color(0xffa5d0bb),
    onTertiaryFixedVariant: Color(0xff264e3e),
    surfaceDim: Color(0xffdedacd),
    surfaceBright: Color(0xfffef9ec),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff8f4e6),
    surfaceContainer: Color(0xfff2eee0),
    surfaceContainerHigh: Color(0xffece8db),
    surfaceContainerHighest: Color(0xffe6e2d5),
  );
}
